---
abstract: 'simple pocketio client'
author:
  - 'Makamaka Hannyaharamitu, E<lt>makamaka[at]cpan.orgE<gt>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PocketIO-Client-IO
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 0
  Plack: 0
  PocketIO: 0.13
  Test::More: 0
  Test::TCP: 0
  Twiggy: 0
resources:
  repository: http://github.com/makamaka/AnyEvent-PocketIO-Client/
version: 0.01
